services:
  postgres:
    image: postgres:17
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
  caddy:
    image: caddy:2
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy_data:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    healthcheck:
      test: ["CMD", "caddy", "version"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
  # Enable if tracing is needed
  # lgtm:
  #   image: docker.io/grafana/otel-lgtm:0.11.10
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #     - "4317:4317"
  #     - "4318:4318"
  #   volumes:
  #     - lgtm_grafana:/data/grafana
  #     - lgtm_prometheus:/data/prometheus
  #     - lgtm_loki:/data/loki
  #   environment:
  #     - GF_PATHS_DATA=/data/grafana

volumes:
  postgres_data:
  lgtm_grafana:
  lgtm_prometheus:
  lgtm_loki:
