# fly.toml app configuration file generated on 2024-08-03T22:14:02+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '$APP_NAME'
primary_region = '$PRIMARY_REGION'

[build.args]
VITE_API_URL = '$VITE_API_URL'

[env]
PORT = '8000'
BASE_URL = '$BASE_URL'
ZUPASS_ZAPP_NAME = '$ZUPASS_ZAPP_NAME'
ZUPASS_URL = '$ZUPASS_URL'
SENTRY_DSN = '$SENTRY_DSN'
VERIFIER_ENDPOINT = '$VERIFIER_ENDPOINT'
DATABASE_MAX_POOL_SIZE = '$DATABASE_MAX_POOL_SIZE'
GRAFANA_URL = '$GRAFANA_URL'
ENVIRONMENT = '$ENVIRONMENT'

[processes]
app = 'task start'

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 4
processes = ['app']

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/api/v1/conferences"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"

[[statics]]
guest_path = "/app/public/assets"
url_prefix = "/assets"
