# fly.toml app configuration file generated for verifier-dev on 2024-11-03T15:38:58+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '$VERIFIER_APP_NAME'
primary_region = '$PRIMARY_REGION'

[build]

[http_service]
internal_port = 3000
force_https = false
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 2
processes = ['app']

[[vm]]
cpu_kind = "performance"
cpus = 1
memory = "2gb"
